[workspace]
members = ["contracts/*", "packages/*"]
resolver = "2"

[workspace.package]
authors       = ["Sturdy <sturdy@apollo.farm>"]
edition       = "2021"
license       = "MPL-2.0"
homepage      = "https://apollo.farm"
repository    = "https://github.com/apollodao/liquidity-helpers"
documentation = "https://docs.rs/liquidity-helpers"
keywords      = ["blockchain", "cosmos", "cosmwasm"]
rust-version  = "1.64.0"

[workspace.dependencies]
cosmwasm-schema  = "1.2.1"
cosmwasm-std     = "1.2.1"
cw2              = "1.0.1"
cw20             = "1.0.1"
cw-storage-plus  = "1.0.1"
thiserror        = "1.0.38"
schemars         = "0.8.11"
serde            = { version = "1.0.145", default-features = false, features = ["derive"] }
apollo-cw-asset  = "0.1.0"
cw-dex           = "0.1.0"
apollo-utils     = "0.1.0"
liquidity-helper = { path = "./packages/liquidity-helper" }

# Dev dependencies
osmosis-testing = { git = "https://github.com/apollodao/osmosis-rust.git", rev = "430236bd63f26d618e11e59709a56c808c4d427c" }
cw-it           = { git = "https://github.com/apollodao/cw-it", rev = "cc1b973" }
test-case       = "3.0.0"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
rpath            = false
