[workspace]
members = ["contracts/*", "packages/*"]
resolver = "2"

[workspace.package]
edition       = "2021"
license       = "MPL-2.0"
homepage      = "https://apollo.farm"
repository    = "https://github.com/apollodao/liquidity-helpers"
keywords      = ["cosmwasm", "liquidity", "provision", "osmosis", "astroport"]
rust-version  = "1.64.0"

[workspace.dependencies]
cosmwasm-schema  = "1.2.1"
cosmwasm-std     = "1.2.1"
cw2              = "1.0.1"
cw20             = "1.0.1"
cw-storage-plus  = "1.0.1"
thiserror        = "1.0.38"
schemars         = "0.8.11"
serde            = { version = "1.0.145", default-features = false, features = ["derive"] }
apollo-cw-asset  = "0.1.0"
cw-dex           = "0.1.0"
apollo-utils     = "0.1.0"
liquidity-helper = { path = "./packages/liquidity-helper" }

# Dev dependencies
osmosis-test-tube = { git = "https://github.com/apollodao/test-tube.git", rev = "d2245dfed56329d8c2e84d109a5a01f29d0db0e8" }
cw-it           = { git = "https://github.com/apollodao/cw-it", rev = "cc1b973" }
test-case       = "3.0.0"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
rpath            = false
