[package]
name          = "liquidity-helper"
description   = "Helpers and common messaging for liquidity helper contracts"
authors       = ["Sturdy <sturdy@apollo.farm>"]
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
homepage      = { workspace = true }
repository    = { workspace = true }
documentation = "https://docs.rs/liquidity-helpers"
keywords      = { workspace = true }
rust-version  = { workspace = true }
readme        = "README.md"

[dependencies]
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }
apollo-cw-asset  = { workspace = true }
apollo-utils     = { workspace = true }
cw20             = { workspace = true }
