name: Integration Test Suite
on:
  pull_request:
  workflow_dispatch:

env:
  RUSTFLAGS: -D warnings

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65.0
          target: wasm32-unknown-unknown
          override: true

      - name: Compile contracts
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-unknown-unknown --lib --release
        env:
          RUST_BACKTRACE: 1

      - name: Run Osmosis Integration Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test osmosis_integration_tests
        env:
          RUST_BACKTRACE: 1

      - name: Run Astroport Integration Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test astroport_integration_tests
        env:
          RUST_BACKTRACE: 1
